Class_system_Backstage_pj/Areas/student_management/Controllers/MemberController.cs
using Class_system_Backstage_pj.Areas.student_management.Models.DTO;
using Class_system_Backstage_pj.Areas.student_management.ViewModel;
using Class_system_Backstage_pj.Models;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Cryptography;
using System.Text;


namespace Class_system_Backstage_pj.Areas.student_management.Controllers
{
    [Area("student_management")]
    public class MemberController : Controller
    {
        private readonly ILogger<MemberController> _logger;
        private readonly studentContext _studentContext;

        public MemberController(ILogger<MemberController> logger, studentContext studentContext)
        {
            _logger = logger;
            _studentContext = studentContext;
        }


        public IActionResult Index()
        {
            return View();
        }




        // GET: api/Member
        [HttpGet]
        public IActionResult GetAllStudent()
        {
            //return Ok(members);
            var members = _studentContext.T會員學生s.ToList();
            return View(members);
        }

        public IActionResult GetAllStudentJson()
        {
            var members = _studentContext.T會員學生s;
            return Json(members);

        }


        public IActionResult CheckStudentEmail(T會員學生 user)
        {
            bool isDuplicate = _studentContext.T會員學生s.Any(p => p.信箱 == user.信箱);
            return Content($"{isDuplicate}", "text/plain", Encoding.UTF8);
        }


        // GET: api/Member/5
        [HttpGet("{id}")]
        public IActionResult GetStudentById(int id)
        {
            var member = _studentContext.T會員學生s.Find(id);
            if (member == null)
            {
                return NotFound();
            }
            return Ok(member);
        }


        public IActionResult RegisterStudent()
        {
            return View();
        }

        // POST: api/Member
        [HttpPost]
        public IActionResult RegisterStudent(MemberRegisterDTO memberRegisterinfo)
        {

            //if (!ModelState.IsValid)
            //{
            //    return View(memberRegisterinfo);
            //}

            byte[]? _filebyte = null;

            if (memberRegisterinfo.圖片 != null && memberRegisterinfo.圖片.Length > 0)
            {
                using (var memoryStream = new MemoryStream())
                {
                    // 將圖片數據讀取到內存流中
                    memberRegisterinfo.圖片.CopyTo(memoryStream);

                    // 將內存流中的數據轉換為 byte 陣列
                    _filebyte = memoryStream.ToArray();
                }
            }

            string _salt = GenerateSalt();
            string _hashPassword = HashPassword(memberRegisterinfo.密碼, _salt);

            var memberEntity = new T會員學生
            {
                姓名 = memberRegisterinfo.姓名,
                性別 = memberRegisterinfo.性別,
                身分證字號 = memberRegisterinfo.身分證字號,
                信箱 = memberRegisterinfo.信箱,
                手機 = memberRegisterinfo.手機,
                地址 = memberRegisterinfo.地址,
                生日 = memberRegisterinfo.生日,
                學校 = memberRegisterinfo.學校,
                科系 = memberRegisterinfo.科系,
                學位 = memberRegisterinfo.學位,
                畢肄 = memberRegisterinfo.畢肄,
                圖片 = _filebyte,
                密碼 = _hashPassword,
                Salt = _salt,
                註冊日期 = DateTime.Now,
                修改日期 = DateTime.Now,
            };



            try
            {
                _studentContext.T會員學生s.Add(memberEntity);
                _studentContext.SaveChanges();

                return Ok(new { message = "註冊成功", name = memberRegisterinfo.姓名 });
            }
            catch (Exception ex)
            {
                return BadRequest(new { message = "註冊失敗", error = ex.Message, name = memberRegisterinfo.姓名 });
            }
        }

        //創造鹽 (亂碼)
        private string GenerateSalt()
        {
            using (RandomNumberGenerator rng = RandomNumberGenerator.Create())
            {
                byte[] salt = new byte[16];
                rng.GetBytes(salt);
                return Convert.ToBase64String(salt);//轉成base64字串
            }
        }

        //創造Hash
        private string HashPassword(string password, string salt)
        {
            using (SHA256 sha256 = SHA256.Create())// SHA-256 雜湊
            {
                byte[] combined = Encoding.UTF8.GetBytes(password + salt);
                byte[] hashedBytes = sha256.ComputeHash(combined);
                return Convert.ToBase64String(hashedBytes);
            }
        }

        // PUT: api/Member/5
        [HttpPut("{id}")]
        public IActionResult UpdateStudent(int id, T會員學生 updatedMember)
        {
            if (id != updatedMember.學生id)
            {
                return BadRequest();
            }

            var existingMember = _studentContext.T會員學生s.Find(id);
            if (existingMember == null)
            {
                return NotFound();
            }

            existingMember = updatedMember;
            _studentContext.SaveChanges();

            return NoContent();
        }


        // DELETE: api/Member/5 先封印這方法
        //[HttpDelete("{id}")]
        //public IActionResult DeleteMember(int id)
        //{
        //    var member = _studentContext.T會員學生s.Find(id);
        //    if (member == null)
        //    {
        //        return NotFound();
        //    }

        //    _studentContext.T會員學生s.Remove(member);
        //    _studentContext.SaveChanges();

        //    return NoContent();
        //}



    }
}

Class_system_Backstage_pj/Areas/student_management/Views/Member/GetAllStudent.cshtml
@model IEnumerable<T會員學生>

@{
    ViewData["Title"] = "學員資料管理";
}

@section Styles
{
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.7/css/jquery.dataTables.css" />
    @* <script src="https://cdn.datatables.net/1.13.7/js/jquery.dataTables.js"></script> *@
    <link href="~/css/datatablesinline.css" rel="stylesheet" />
    <style>
        /*  頭部表格欄位樣式 */
        .imthead {
            background-color: #C4E1E1;
            font-weight: 700;
        }
        /*  新刪修按鈕排列方式 */
        .crudlist {
            display: flex;
            align-items: center;
            grid-gap: 10px;
        }
            /*  新刪修按鈕大小微調 */
            .crudlist li {
                padding: 15px;
                margin-bottom: 0;
            }
    </style>
}

<div class="header">
    <!-- 主頁上方操作流程序，記得有新增頁面時要記得編輯 -->
    <div class="left">
        <h1>@ViewData["Title"]</h1>
        <ul class="breadcrumb">
            <li><a asp-area="" asp-controller="Home" asp-action="Index">首頁</a></li>
            /
            <li><a asp-area="student_management" asp-controller="Member" asp-action="Index">學員管理系統</a></li>
            /
            <li><a href="#" class="active">@ViewData["Title"]</a></li>
        </ul>
    </div>
    <!-- 主頁上方操作流程序-->
</div>

<div>
    <ul class="crudlist">
        <li>
            @* <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#staticBackdrop">新增</button> *@
            <a asp-area="student_management" asp-controller="Member" asp-action="RegisterStudent" class="btn btn-primary">新增</a>

        </li>
@*         <li><button class="btn btn-primary">刪除</button></li>
        <li><button class="btn btn-secondary">修改</button></li> *@
    </ul>
</div>

@* <div class="bottom-data">
    <div class="orders">
        <div class="header">
            <i class='bx bx-receipt'></i>
            <h3>學生資訊</h3>
        </div>

        <table id="member_table" class="display">
            <thead class="imthead">
                <tr>
                    <th>姓名</th>
                    <th>性別</th>
                    <th>信箱</th>
                    <th>手機</th>
                    <th>狀態</th>
                    <th>鎖定</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var member in Model)
                {
                    <tr>
                        <td>@member.姓名</td>
                        <td>@member.性別</td>
                        <td>@member.信箱</td>
                        <td>@member.手機</td>
                        <td>@member.狀態</td>
                        <td>@member.鎖定</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>
 *@
<div class="bottom-data">
    <div class="orders">
        <div class="header">
            @* 表格標題輸入地方 *@
            <i class='bx bx-receipt'></i> <!-- 表格的小icon -->
            <h3>學生資訊</h3> <!-- 表格的名稱 -->
            @*             <i class='bx bx-filter'></i>
            <i class='bx bx-search'></i>  *@

        </div>
        @* 表格內容輸入地方 *@
        <table id="test_table">
            <thead class="imthead">
                <tr>
                    <td>@Html.DisplayNameFor(model => model.姓名)</td>
                    <td>@Html.DisplayNameFor(model => model.性別)</td>
                    <td>@Html.DisplayNameFor(model => model.信箱)</td>
                    <td>@Html.DisplayNameFor(model => model.手機)</td>
                    <td>@Html.DisplayNameFor(model => model.地址)</td>
                    <td>@Html.DisplayNameFor(model => model.狀態)</td>
                    <td>@Html.DisplayNameFor(model => model.鎖定)</td>
                </tr>
            </thead>
            @* 表格內容輸入地方 *@
        </table>
        @* 表格輸入結束 *@
    </div>
</div>



<!-- Button trigger modal -->
<!-- 按下新增的觸發 -->
<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered .modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">Modal title</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                ...
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">儲存送出</button>
            </div>
        </div>
    </div>
</div>



@section Scripts
{
    <script src="~/lib/datatables/js/jquery.datatables.min.js"></script>
    <script src="//cdn.datatables.net/fixedheader/3.4.0/js/dataTables.fixedHeader.min.js"> </script>
    <script>
        $(document).ready(function () {
            // alert("ready")
            $("table").dataTable({
                autoWidth: false,
                ajax: {
                    type: 'GET',
                    url: "/student_management/Member/GetAllStudentJson",
                    dataSrc: function (json) {
                        return json;
                    }
                },
                columns: [
                    { "data": "姓名", "width": "10 %" },
                    { "data": "性別", "width": "5 %" },
                    { "data": "信箱", "width": "10 %" },
                    { "data": "手機", "width": "10 %" },
                    { "data": "地址", "width": "20 %" },
                    { "data": "狀態", "width": "5 %" },
                    { "data": "鎖定", "width": "5 %" },
                    { "data": "學生id", "visible": false }, //放入表格pk但不要顯示，為了在row中引用
                    {
                        data: null,
                        title: "function",
                        render: function (data, type, row) 
                        {
                            return '<i class="bx bxs-message-square-edit" data-id="' + row.學生id + '"></i>'
                                // + '<i class="bx bxs-trash-alt"data-id="' + row.學生id + '" ></i>'
                            //引入icon與表格pk識別
                            //return '<button class="btn btn-danger btn-sm delete-btn" data-id="' + row.店家id + '">刪除</button>';
                        }
                    }
                ],
                fixedHeader: { header: true },
                language: {
                    url: '//cdn.datatables.net/plug-ins/1.13.7/i18n/zh-HANT.json'
                },
            });

            $('#test_table tbody').on('click', 'i.bxs-trash-alt', async function () {
                var productId = $(this).data('id');
                // console.log(productId)
                // const url = `@Url.Content("~/Products/DeleteStore/")?id=${productId}`;
                // const response = await fetch(url);
                // const data = await response.text();
                console.log(productId);
            });

            // $('#test_table tbody').on('click', 'i.bxs-message-square-edit', async function () {
            //     var productId = $(this).data('id');
            //     // console.log(productId)
            //     // const url = `@Url.Content("~/Products/DeleteStore/")?id=${productId}`;
            //     // const response = await fetch(url);
            //     // const data = await response.text();
            //     console.log(productId);
            // });
            
        })
    </script>
}

Class_system_Backstage_pj/Areas/student_management/Views/Member/Index.cshtml
@{
    ViewData["Title"] = "學員管理系統";
}
@section Styles
{
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.7/css/jquery.dataTables.css" />
    @* <script src="https://cdn.datatables.net/1.13.7/js/jquery.dataTables.js"></script> *@
    @* <link href="~/css/datatablesinline.css" rel="stylesheet" /> *@
    <link href="~/css/datatablesinline.min.css" rel="stylesheet" />
    <style>
        .imthead {
            background-color: #C4E1E1;
            font-weight: 700;
        }
    </style>
}
<div class="header">
    <!-- 主頁上方操作流程序能引入操作流程返回，記得有新增頁面時要記得編輯，有class="active的是現在位置-->
    <div class="left">
        <h1> @ViewData["Title"]</h1>
        <ul class="breadcrumb">
            <li>
                <a asp-area="" asp-controller="Home" asp-action="Index"> 首頁 </a>
            </li>
            /
            <li><a href="#" class="active">@ViewData["Title"]</a></li>
        </ul>
    </div>
    <!-- 主頁上方操作流程序結束-->
</div>

<!-- Insights -->
<ul class="insights">
    <li>
        <i class='bx bx-cool'></i>
        <a asp-area="student_management" asp-controller="Member" asp-action="GetAllStudent">
            <span class="info">
                <h3>
                    學生資料管理
                </h3>
                <p></p>
            </span>
        </a>
    </li>
    <li>
        <i class='bx bx-show-alt'></i>
        <span class="info">
            <h3>
                老師資料管理
            </h3>
            <p></p>
        </span>
    </li>
    <li>
        <i class='bx bx-line-chart'></i>
        <span class="info">
            <h3>
                備用欄位1
            </h3>
            <p></p>
        </span>
    </li>
    <li>
        <i class='bx bx-dollar-circle'></i>
        <span class="info">
            <h3>
                備用欄位2
            </h3>
            <p></p>
        </span>
    </li>
</ul>
<!-- End of Insights -->
@* 表格標題輸入地方 *@
@* <div class="bottom-data">
    <div class="orders">
        <div class="header">
            <i class='bx bx-receipt'></i>  <!-- 表格的小icon -->
            <h3>Recent Orders</h3> <!-- 表格的名稱 -->
        </div>

        <table>
            <thead>
                <tr>
                    <th>User</th>
                    <th>Order Date</th>
                    <th>Status</th>
                </tr>
            </thead>
            <!-- 表格標題輸入地方 -->
            <tbody>
                <tr>
                    <td>
                        <img src="images/profile-1.jpg">
                        <p>John Doe</p>
                    </td>
                    <td>14-08-2023</td>
                    <td><span class="status completed">Completed</span></td>
                </tr>
                <tr>
                    <td>
                        <img src="images/profile-1.jpg">
                        <p>John Doe</p>
                    </td>
                    <td>14-08-2023</td>
                    <td><span class="status pending">Pending</span></td>
                </tr>
                <tr>
                    <td>
                        <img src="images/profile-1.jpg">
                        <p>John Doe</p>
                    </td>
                    <td>14-08-2023</td>
                    <td><span class="status process">Processing</span></td>
                </tr>
            </tbody>
        </table>
    </div> *@
@* 表格輸入結束 *@



<!-- 側邊條列區塊 -->
@*     <div class="reminders">
        <div class="header">
            <i class='bx bx-note'></i>
            <h3>Remiders</h3>
            <i class='bx bx-filter'></i>
            <i class='bx bx-plus'></i>
        </div>
        <ul class="task-list">
            <li class="completed">
                <div class="task-title">
                    <i class='bx bx-check-circle'></i>
                    <p>Start Our Meeting</p>
                </div>
                <i class='bx bx-dots-vertical-rounded'></i>
            </li>
            <li class="completed">
                <div class="task-title">
                    <i class='bx bx-check-circle'></i>
                    <p>Analyse Our Site</p>
                </div>
                <i class='bx bx-dots-vertical-rounded'></i>
            </li>
            <li class="not-completed">
                <div class="task-title">
                    <i class='bx bx-x-circle'></i>
                    <p>Play Footbal</p>
                </div>
                <i class='bx bx-dots-vertical-rounded'></i>
            </li>
        </ul>
    </div> *@

<!-- End of Reminders-->
</div>


@section Scripts
{


}

Class_system_Backstage_pj/Areas/student_management/Views/Member/RegisterStudent.cshtml
@using Class_system_Backstage_pj.Areas.student_management.Models.DTO
@* @model Class_system_Backstage_pj.Models.T會員學生 *@
@model MemberRegisterDTO

@{
    ViewData["Title"] = "新增學員";
}

<div class="header">
    <!-- 主頁上方操作流程序，記得有新增頁面時要記得編輯 -->
    <div class="left">
        <h1>@ViewData["Title"]</h1>
        <ul class="breadcrumb">
            <li><a asp-area="" asp-controller="Home" asp-action="Index">首頁</a></li>
            /
            <li><a asp-area="student_management" asp-controller="Member" asp-action="Index">學員管理系統</a></li>
            /
            <li><a asp-area="student_management" asp-controller="Member" asp-action="GetAllStudent">學員資料管理</a></li>
            /
            <li><a href="#" class="active">@ViewData["Title"]</a></li>
        </ul>
    </div>
    <!-- 主頁上方操作流程序-->
</div>

<hr />

<div class="row">
    <div class="col-md-4">
        <form id="userForm">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label for="UserName" class="form-label">姓名：</label>
                <input type="text" asp-for="姓名" class="form-control" id="UserName" />
                <span asp-validation-for="姓名" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label for="UserGender" class="form-label">性別：</label>
                <select asp-for="性別" class="form-control" id="UserGender" style="width: 50px;">
                    <option value="男">男</option>
                    <option value="女">女</option>
                </select>
                <span asp-validation-for="性別" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label for="UserIdentity" class="form-label">身分證字號：</label>
                <input type="text" asp-for="身分證字號" class="form-control" id="UserIdentity" />
                <span asp-validation-for="身分證字號" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label for="UserEmail" class="form-label">信箱：</label>
                <input type="email" asp-for="信箱" class="form-control" id="UserEmail" />
                <span asp-validation-for="信箱" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label for="UserPhone" class="form-label">手機：</label>
                <input type="text" asp-for="手機" class="form-control" id="UserPhone" />
                <span asp-validation-for="手機" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label for="UserAddress" class="form-label">地址：</label>
                <input type="text" asp-for="地址" class="form-control" id="UserAddress" style="width: 300px;" />
                <span asp-validation-for="地址" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label for="UserPassword" class="form-label">密碼：</label>
                <input type="password" asp-for="密碼" class="form-control" id="UserPassword" />
                <span asp-validation-for="密碼" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label for="UserPasswordCheck" class="form-label">密碼驗證：</label>
                <input type="password" asp-for="密碼驗證" class="form-control" id="UserPasswordCheck" />
                <span asp-validation-for="密碼驗證" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label for="UserImage" class="form-label">圖片 (只接受PNG 或 JPG)：</label>
                <input type="file" asp-for="圖片" class="form-control" id="UserImage" accept=".png, .jpg, .jpeg" />
                <span asp-validation-for="圖片" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label for="UserBirthday" class="form-label">生日：</label>
                <input type="date" asp-for="生日" class="form-control" id="UserBirthday" />
                <span asp-validation-for="生日" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label for="UserSchool" class="form-label">學校：</label>
                <input type="text" asp-for="學校" class="form-control" id="UserSchool" />
                <span asp-validation-for="學校" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label for="UserDepartment" class="form-label">科系：</label>
                <input type="text" asp-for="科系" class="form-control" id="UserDepartment" />
                <span asp-validation-for="科系" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label for="UserDegree" class="form-label">學位：</label>
                <select asp-for="學位" class="form-control" id="UserDegree" style="width: 80px;">
                    <option value="國小">國小</option>
                    <option value="國中">國中</option>
                    <option value="高中">高中</option>
                    <option value="大學">大學</option>
                    <option value="碩士">碩士</option>
                    <option value="博士">博士</option>
                </select>
                <span asp-validation-for="學位" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label for="UserGraduation" class="form-label">畢業肄業：</label>
                <select asp-for="畢肄" class="form-control" id="UserGraduation" style="width: 80px;">
                    <option value="畢業">畢業</option>
                    <option value="肄業">肄業</option>
                </select>
                <span asp-validation-for="畢肄" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input id="submitBtn" type="submit" value="送出" class="btn btn-primary" />
            </div>
        </form>
        <br /><br />
    </div>
</div>

@* 範例
    <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered .modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">Modal title</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                ...
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">儲存送出</button>
            </div>
        </div>
    </div>
</div> *@

<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered .modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">預設標題~~~~</h5>
                @* <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button> *@
            </div>
            <div class="modal-body">
                <p id="modalMessage">預設訊息~~~~~~~~</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">關閉</button>
            </div>
        </div>
    </div>
</div>





@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script>
        const btn = document.querySelector('#submitBtn');
        btn.addEventListener('click', async (event) => {
            event.preventDefault(); //防止預設行為的發生，提交、跳轉.冒泡??.等
            const userForm = document.querySelector('#userForm');
            const formData = new FormData(userForm);

            const url = '@Url.Content("/student_management/Member/RegisterStudent")';
            try {
                const response = await fetch(url, {
                    method: 'POST',
                    body: formData
                });

                const data = await response.json();

                if (response.ok) {
                    $('#staticBackdropLabel').text('註冊成功');
                    $('#modalMessage').text('學生: ' + data.name + ' 註冊成功');//後端回傳的name
                    $('#staticBackdrop').modal('show');
                    userForm.reset();//清除
                } else {
                    $('#staticBackdropLabel').text('註冊失敗');
                    $('#modalMessage').text(data.message + '學生: ' + data.name);
                    $('#staticBackdrop').modal('show');
                }
            } catch (error) {
                console.error('發生錯誤:', error);
            }
        })

    </script>
}