Class_system_Backstage_pj/Areas/job_vacancy/Controllers/ResumeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Class_system_Backstage_pj.Models;
using Class_system_Backstage_pj.Areas.job_vacancy.ViewModels;
using Microsoft.AspNetCore.Http;
using Newtonsoft.Json;
using System.Text;

namespace Class_system_Backstage_pj.Areas.job_vacancy.Controllers
{
    [Area("job_vacancy")]
    [Route("/job_vacancy/Resume/{Action=Index}/{resumeID?}")]
    public class ResumeController : Controller
    {
        private readonly studentContext _context;

        public ResumeController(studentContext context)
        {
            _context = context;
        }

        // GET: job_vacancy/Resume
        public IActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// 新增履歷1：輸入學生身分證號，確認學生存在並提取部分學生資料。
        /// </summary>
        /// <param name="IDnumber">學生的身分證號</param>
        // POST: job_vacancy/Resume/CreateVerify/5
        [HttpPost]
        public async Task<IActionResult> CreateVerify(string IDnumber)
        {
            try
            {
                var theStudent = await _context.T會員學生s.FirstOrDefaultAsync(data => data.身分證字號 == IDnumber);

                if (theStudent != null)
                {
                    var viewModel = new ResumeCreateViewModel
                    {
                        StudentID = theStudent.學生id,
                        Name = theStudent.姓名,
                        ResumeTitle = theStudent.姓名 + "的履歷",
                        Photo = theStudent.圖片,
                        Gender = theStudent.性別,
                        Birth = theStudent.生日,
                        Email = theStudent.信箱,
                        Phone = theStudent.手機,
                        School = theStudent.學校,
                        Department = theStudent.科系,
                        Academic = theStudent.學位,
                        Graduated = theStudent.畢肄
                    };

                    // 將 viewModel 存到 Session 中，用於後續使用
                    var viewModelJson = JsonConvert.SerializeObject(viewModel);
                    var viewModelBytes = Encoding.UTF8.GetBytes(viewModelJson);
                    HttpContext.Session.Set("ResumeViewModel", viewModelBytes);

                    return Json(new { success = true, redirectUrl = Url.Action("Create", "Resume") });
                }
                else
                {
                    // 如果學生不存在，返回查無此學生
                    return Json(new { success = false, message = $"查無此學生 {IDnumber}" });
                }
            }
            catch (Exception ex)
            {
                // 如果發生異常，返回問題詳細訊息
                return Problem(detail: ex.Message + "異常");
            }
        }

        /// <summary>
        /// 新增履歷2：負責返回視圖。
        /// </summary>
        // GET: job_vacancy/Resume/Create
        public IActionResult Create()
        {
            //取出存在Session的資料
            var viewModelBytes = HttpContext.Session.Get("ResumeViewModel");
            if (viewModelBytes != null)
            {
                var viewModelJson = Encoding.UTF8.GetString(viewModelBytes);
                var viewModel = JsonConvert.DeserializeObject<ResumeCreateViewModel>(viewModelJson);
                return View(viewModel);
            }
            else
            {
                return NotFound();
            }
        }

        /// <summary>
        /// 新增履歷3：將前端傳回的資料進行驗證，通過後存入資料庫。
        /// </summary>
        /// <param name="viewModel"></param>
        // POST: job_vacancy/Resume/CreateResume
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateResume(
            [Bind("StudentID, Name, Birth, Photo, Gender, Phone, Email, School, Academic, Department, Graduated, ResumeTitle, ResumeStatus, HopeJobTitle, HopeSalary, HopeLocation, Skill, Language, WorkExperience, WorkType, WorkTime, WorkShift, Autobiography")] ResumeCreateViewModel viewModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    //更新學生資料
                    var theStudent = await _context.T會員學生s.FindAsync(viewModel.StudentID);
                    if (theStudent == null)
                    {
                        return NotFound();
                    }

                    byte[]? photoData = await ReadUploadImage(Request.Form.Files["Photo"], null);

                    theStudent.姓名 = viewModel.Name;
                    theStudent.圖片 = photoData;
                    theStudent.性別 = viewModel.Gender;
                    theStudent.手機 = viewModel.Phone;
                    theStudent.生日 = viewModel.Birth;
                    theStudent.信箱 = viewModel.Email;
                    theStudent.學校 = viewModel.School;
                    theStudent.學位 = viewModel.Academic;
                    theStudent.科系 = viewModel.Department;
                    theStudent.畢肄 = viewModel.Graduated;
                    theStudent.修改日期 = DateTime.Now;
                    _context.Update(theStudent);

                    // 新增履歷資料
                    var newResume = new T工作履歷資料
                    {
                        F學員Id = viewModel.StudentID,
                        F履歷名稱 = viewModel.ResumeTitle,
                        F履歷狀態 = "公開",
                        F專長技能 = viewModel.Skill,
                        F語文能力 = viewModel.Language,
                        F有無工作經驗 = viewModel.WorkExperience,
                        F工作性質 = viewModel.WorkType,
                        F工作時段 = viewModel.WorkTime,
                        F配合輪班 = viewModel.WorkShift,
                        F希望職稱 = viewModel.HopeJobTitle,
                        F希望薪水待遇 = viewModel.HopeSalary,
                        F希望工作地點 = viewModel.HopeLocation,
                        F自傳 = viewModel.Autobiography,
                        F建立時間 = DateTime.Now,
                        F最後更新時間 = DateTime.Now,
                        F刪除狀態 = "0",
                        F刪除或關閉原因 = "0"
                    };

                    // 將新的履歷添加到資料庫中
                    _context.T工作履歷資料s.Add(newResume);
                    await _context.SaveChangesAsync();

                    return Json(new { redirectUrl = Url.Action("Index", "Resume") });

                }
                else
                {
                    string errorMessage = string.Join("；", ModelState.Values
                                        .SelectMany(v => v.Errors)
                                        .Select(e => e.ErrorMessage));
                    return Json(new { success = false, message = errorMessage });
                }
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = "發生異常：" + ex.Message });
            }
        }

        /// <summary>
        /// 編輯履歷1：根據履歷編號提取相應的資料，並返回視圖。
        /// </summary>
        /// <param name="resumeID">履歷ID</param>
        // GET: job_vacancy/Resume/Edit/5
        public async Task<IActionResult> Edit(int resumeID)
        {
            var thisResume = await _context.T工作履歷資料s.FindAsync(resumeID);
            
            if (thisResume == null)
            {
                return NotFound("無這筆資料");
            }

            var theStudent = await _context.T會員學生s.FirstOrDefaultAsync(data => data.學生id == thisResume.F學員Id);
            if (theStudent == null)
            {
                return NotFound("無這筆資料");
            }

            var viewModel = new ResumeCreateViewModel
            {
                ResumeID = resumeID,
                StudentID = thisResume.F學員Id,

                Name = theStudent.姓名,
                Photo = theStudent.圖片,
                Gender = theStudent.性別,
                Birth = theStudent.生日,
                Email = theStudent.信箱,
                Phone = theStudent.手機,
                School = theStudent.學校,
                Department = theStudent.科系,
                Academic = theStudent.學位,
                Graduated = theStudent.畢肄,

                ResumeTitle = thisResume.F履歷名稱,
                ResumeStatus = thisResume.F履歷狀態,
                Skill = thisResume.F專長技能,
                Language = thisResume.F語文能力,
                WorkExperience = thisResume.F有無工作經驗,
                WorkType = thisResume.F工作性質,
                WorkTime = thisResume.F工作時段,
                WorkShift = thisResume.F配合輪班,
                HopeJobTitle = thisResume.F希望職稱,
                HopeSalary = thisResume.F希望薪水待遇,
                HopeLocation = thisResume.F希望工作地點,
                Autobiography = thisResume.F自傳,
            };
            return View(viewModel);
        }

        /// <summary>
        /// 編輯履歷2：更新資料庫的履歷資料。
        /// </summary>
        /// <param name="resumeID">履歷ID</param>
        /// <param name="viewModel">包含更新資訊的履歷視圖模型</param>
        // POST: job_vacancy/Resume/UpdateResume/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateResume(int resumeID,
            [Bind("ResumeID, StudentID, Name, Birth, Photo, Gender, Phone, Email, School, Department, Academic, Graduated, ResumeTitle, ResumeStatus, HopeJobTitle, HopeSalary, HopeLocation, Skill, Language, WorkExperience, WorkType, WorkTime, WorkShift, Autobiography")] ResumeCreateViewModel viewModel)
        {
            try
            {
                var thisResume = await _context.T工作履歷資料s.FindAsync(resumeID);
                if (thisResume == null || resumeID != viewModel.ResumeID)
                {
                    return NotFound();
                }

                var theStudent = await _context.T會員學生s.FindAsync(thisResume.F學員Id);
                if (theStudent == null)
                {
                    return NotFound();
                }

                if (ModelState.IsValid)
                {
                    //更新學生資料
                    var originalPhoto = theStudent.圖片;

Class_system_Backstage_pj/Areas/job_vacancy/Controllers/jobHomeController.cs
using Class_system_Backstage_pj.Models;
using Microsoft.AspNetCore.Mvc;

namespace Class_system_Backstage_pj.Areas.job_vacancy.Controllers
{
    [Area("job_vacancy")]
    public class jobHomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Resume()
        {
            return View();
        }
        public IActionResult Company()
        {
            return View();
        }
        public IActionResult Vacancy()
        {
            return View();
        }
    }
}

Class_system_Backstage_pj/Areas/job_vacancy/Views/jobHome/Company.cshtml
@{
    ViewData["Title"] = "公司帳戶管理";
}
<h1>@ViewData["Title"]</h1>

Class_system_Backstage_pj/Areas/job_vacancy/Views/jobHome/Index.cshtml
@{
    ViewData["Title"] = "工作媒合管理";
}
@section Styles
{
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.7/css/jquery.dataTables.css" />
    @* <script src="https://cdn.datatables.net/1.13.7/js/jquery.dataTables.js"></script> *@
    @* <link href="~/css/datatablesinline.css" rel="stylesheet" /> *@
    <link href="~/css/datatablesinline.min.css" rel="stylesheet" />
    <style>
        .imthead {
            background-color: #C4E1E1;
            font-weight: 700;
        }

    </style>
}
<div class="header">
    <!-- 主頁上方操作流程序能引入操作流程返回，記得有新增頁面時要記得編輯，有class="active的是現在位置-->
    <div class="left">
        <h1> @ViewData["Title"]</h1>
        <ul class="breadcrumb">
            <li>
                <a asp-area="" asp-controller="Home" asp-action="Index"> 首頁 </a>
            </li>
            /
            <li><a href="#" class="active">@ViewData["Title"]</a></li>
        </ul>
    </div>
    <!-- 主頁上方操作流程序結束-->
</div>

<!-- Insights -->
<ul class="insights">
    <li>
        <i class='bx bx-file'></i>
        <a asp-area="job_vacancy" asp-controller="Resume" asp-action="Index">
            <span class="info">
                <h3>
                    履歷管理
                </h3>
                <p id="resumeCount"></p>
            </span>
        </a>
    </li>
    <li>
        <i class='bx bxs-lock'></i>
        <a asp-area="job_vacancy" asp-controller="jobHome" asp-action="Index">
            <span class="info">
                <h3>
                    公司帳戶管理
                </h3>
                <p style="font-style:italic">待解鎖</p>
            </span>
        </a>
    </li>
    <li>
        <i class='bx bxs-lock'></i>
        <a asp-area="job_vacancy" asp-controller="jobHome" asp-action="Index">
            <span class="info">
                <h3>
                    職缺管理
                </h3>
                <p style="font-style:italic">待解鎖</p>
            </span>
        </a>
    </li>
</ul>
<!-- End of Insights -->

@section Scripts {
    <script>
        $(document).ready(function () {
            $.ajax({
                url: '@Url.Content("/job_vacancy/API/ResumeSum")',
                type: 'GET',
                success: function (data) {
                    $('#resumeCount').text('目前履歷總數：' + data);
                },
                error: function (xhr, status, error) {
                    console.error(error);
                }
            });
        });
    </script>
}

Class_system_Backstage_pj/Areas/job_vacancy/Views/jobHome/Resume.cshtml
@model ResumeListViewModel
@{
    ViewData["Title"] = "履歷管理";
}

@section Styles
{
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.7/css/jquery.dataTables.css" />
    @* <script src="https://cdn.datatables.net/1.13.7/js/jquery.dataTables.js"></script> *@
    <link href="~/css/datatablesinline.css" rel="stylesheet" />
    <style>
        /*  頭部表格欄位樣式 */
        .imthead {
            background-color: #C4E1E1;
            font-weight: 700;
        }
        /*  新刪修按鈕排列方式 */
        .crudlist {
            display: flex;
            align-items: center;
            grid-gap: 10px;
        }
            /*  新刪修按鈕大小微調 */
            .crudlist li {
                padding: 15px;
                margin-bottom: 0;
            }
    </style>
}

<div class="header">
    <!-- 主頁上方操作流程序，記得有新增頁面時要記得編輯 -->
    <div class="left">
        <h1>@ViewData["Title"]</h1>
        <ul class="breadcrumb">
            <li><a asp-area="job_vacancy" asp-controller="jobHome" asp-action="Index">工作媒合管理</a></li>
            /
            <li><a href="#" class="active">@ViewData["Title"]</a></li>
        </ul>
    </div>
    <!-- 主頁上方操作流程序-->
</div>
<div>
    <ul class="crudlist">
        <li>    
            <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
                新增
            </button>
        </li>
        <li><button class="btn btn-primary">刪除</button></li>
        <li><button class="btn btn-secondary">修改</button></li>
    </ul>
</div>
<div class="bottom-data">
    <div class="orders">
        @* 表格標題 *@
        <div class="header">
            <i class='bx bx-receipt'></i> <!-- 表格的小icon -->
            <h3>履歷一覽</h3>
        </div>
        @* 表格內容 *@
        <table id="test_table">
            <thead class="imthead">
                <tr>
                    <td>@Html.DisplayNameFor(model => model.Name)</td>
                    <td>@Html.DisplayNameFor(model => model.ClassName)</td>
                    <td>@Html.DisplayNameFor(model => model.ResumeTitle)</td>
                    <td>@Html.DisplayNameFor(model => model.HopeJobTitle)</td>
                    <td>@Html.DisplayNameFor(model => model.HopeSalary)</td>
                    <td>@Html.DisplayNameFor(model => model.HopeLocation)</td>
                    <td>@Html.DisplayNameFor(model => model.ResumeStatus)</td>
                    <td>@Html.DisplayNameFor(model => model.LastUpdate)</td>
                </tr>
            </thead>
            @* 表格內容輸入地方 *@
        </table>
        @* 表格結束 *@
    </div>
</div>

<!-- Modal 互動視窗：新增履歷 -->
<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
        <div class="modal-content">
            <!--表單標題-->
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">新增履歷</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <!--表單內容-->
            <div class="modal-body">
                <div class="container-fluid">
                    <!-- 1.學生資料-->
                    <div class="row">
                        <div class="col-md-4">.col-md-4</div>
                        <div class="col-md-4 ms-auto">.col-md-4 .ms-auto</div>
                    </div>
                    <!-- 2.技能能力-->
                    <div class="row">
                        <div class="col-md-3 ms-auto">.col-md-3 .ms-auto</div>
                        <div class="col-md-2 ms-auto">.col-md-2 .ms-auto</div>
                    </div>
                    <!-- 3.工作經驗-->
                    <div class="row">
                        <div class="col-md-6 ms-auto">.col-md-6 .ms-auto</div>
                    </div>
                    <!-- 4.求職條件-->
                    <div class="row">
                        <div class="col-sm-9">
                            Level 1: .col-sm-9
                            <div class="row">
                                <div class="col-8 col-sm-6">
                                    Level 2: .col-8 .col-sm-6
                                </div>
                                <div class="col-4 col-sm-6">
                                    Level 2: .col-4 .col-sm-6
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- 5.自傳-->
                    <div class="row">
                        <div class="col-md-6 ms-auto">.col-md-6 .ms-auto</div>
                    </div>
                </div>
            </div>
            <!--表單腳部-->
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">取消</button>
                <button type="button" class="btn btn-primary">儲存</button>
            </div>
        </div>
    </div>
</div>


@section Scripts
{
    <script src="~/lib/datatables/js/jquery.datatables.min.js"></script>
    <script src="//cdn.datatables.net/fixedheader/3.4.0/js/dataTables.fixedHeader.min.js"> </script>
    <script>
        $(document).ready(function () {
            //限制網頁不要出現卷軸
            document.documentElement.style.overflow = 'hidden';

            //帶入資料進dataTable
            $("table").dataTable({
                autoWidth: false,
                ajax: {
                    type: 'GET',
                    url: "/job_vacancy/api/resume",
                    dataSrc: function (json) {
                        return json;
                    }
                },
                columns: [
                    { "data": "studentName" },
                    { "data": "classes" },
                    { "data": "resumeName" },
                    { "data": "hopeJobTitle" },
                    { "data": "hopeSalary" },
                    { "data": "hopeLocation" },
                    { "data": "resumeStatus" },
                    { "data": "lastUpdate" },
                    { "data": "resumeId", "visible": false }, //放入表格pk但不要顯示，為了在row中引用
                    {
                        data: null,
                        title: "function",
                        render: function (data, type, row) {
                            //引入icon與表格pk識別
                            return `<i class="bx bxs-trash-alt"data-id="${row.resumeId}" ></i>&nbsp;&nbsp;&nbsp;
                                    <i class="bx bxs-message-square-edit" data-id="${row.resumeId}"></i>`
                        }
                    }
                ],
                order: [
                    [7, 'desc'] // 按 lastUpdate 降冪排序 //無作用
                ],
                fixedHeader: { header: true },
                language: {
                    url: '//cdn.datatables.net/plug-ins/1.13.7/i18n/zh-HANT.json'
                },
            });
            $('#test_table tbody').on('click', 'i.bxs-trash-alt', async function () {
                var resumeId = $(this).data('id');
            });

            $('#test_table tbody').on('click', 'i.bxs-message-square-edit', async function () {
                var resumeId = $(this).data('id');
            });
        })
    </script>
}

Class_system_Backstage_pj/Areas/job_vacancy/Views/jobHome/Vacancy.cshtml
@{
    ViewData["Title"] = "職缺管理";
}
<h1>@ViewData["Title"]</h1>